// src/pages/dashboard/Overview.jsx
import { useEffect, useState } from "react";
import StatCard from "../../ui/StatCard";
import { listResources, listModels, listIdeas } from "../../../services/firestore";

export default function Overview() {
  const [stats, setStats] = useState({ resources: 0, models: 0, ideas: 0 });

  useEffect(() => {
    (async () => {
      const [r, m, i] = await Promise.all([listResources(), listModels(), listIdeas()]);
      setStats({ resources: r.length, models: m.length, ideas: i.length });
    })();
  }, []);

  return (
    <div>
      <div className="text-2xl font-bold text-slate-900">Overview</div>
      <div className="mt-1 text-sm text-slate-500">Quick snapshot of stored knowledge.</div>

      <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
        <StatCard label="Resources" value={stats.resources} />
        <StatCard label="Models" value={stats.models} />
        <StatCard label="Ideas" value={stats.ideas} />
      </div>

      <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5">
        <div className="text-sm font-bold text-slate-700">Upload → Chunk → Embed → Store</div>
        <div className="mt-2 text-sm text-slate-600">
          Go to <span className="font-semibold">Resources</span> to upload PDFs/TXT/CSV/JSON; embeddings are generated by backend and stored in Firestore for semantic search.
        </div>
      </div>
    </div>
  );
}
